data_source my_snowflake:
  type: snowflake
  account: isidpartner.ap-northeast-1.aws
  username: DQ_TOOL_SYSTEM_USER
  password: isiden2note
  warehouse: DQ_TOOL_WH
  database: DQ_TOOL_DB
  schema: STG_SCHEMA
